/*
 * Tqtype.h
 *
 *  Created on: 2019年8月20日
 *      Author: root
 */

#ifndef TQTYPE_H_
#define TQTYPE_H_


#define TYKJ_PROCESS_SOCKET1 "Z*MY-SOCKET-TQKJ_001*"
#define TYKJ_PROCESS_SOCKET2 "Z*MY-SOCKET-TQKJ_002*"
#define TYKJ_PROCESS_SOCKET3 "Z*MY-SOCKET-TQKJ_003*"
#define TYKJ_PROCESS_SOCKET4 "Z*MY-SOCKET-TQKJ_004*"
#define TYKJ_PROCESS_SOCKET5 "Z*MY-SOCKET-TQKJ_005*"
#define TYKJ_PROCESS_SOCKET6 "Z*MY-SOCKET-TQKJ_006*"
#define TYKJ_PROCESS_SOCKET7 "Z*MY-SOCKET-TQKJ_007*"
#endif /* TQTYPE_H_ */
